expname: official

path:

  ckpt_path: "./output/{}/ckpt"
  log_path: "./output/{}/log"
  result_path: "./output/{}/result"
  script_path: "./output/{}/script"


optimizer:
  batch_size: 32 # 32 for denoise 128 for grid
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0000001 
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
  init_lr: 0.00625
step:
  total_step: 900000
  log_step: 100
  synth_step: 1500
  val_step: 2000
  save_step: 10000
