dataset: "LibriTTS"

path:
  corpus_path: "/data/conggaoxiang/Chem"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "/data/conggaoxiang/Chem"
  preprocessed_path: "/data1/home/zhangzhedong/preprocessed_data/LibriTTS"
 

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 22050 # To make a fair comparison with V2C-Net, we support the sampling rate of 22050Hz for the Chem dataset.
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    # hop_length: 220 # For adapt the sampling rate of 22050Hz
    # win_length: 880 # For adapt the sampling rate of 22050Hz
    hop_length: 256
    win_length: 1024
    
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "frame_level" # Fixed this setting, and our method can not support 'phoneme_level'.
    normalization: True
  energy:
    feature: "frame_level" # Fixed this setting, and our method can not support 'phoneme_level'.
    normalization: True
  emotion:
    n_emotion: 8

Padding:
  preprocess: True  # False, padding for mel, pitch, energy, and duration

last_n_speaker: 0 # number of speakers on the last dataset
with_gt: False # when generating speech by synthesize.py, whether synthesize gt as well
